In [ ]:
import pandas as pd

In [ ]:
my_series=pd.Series([1,2,5,8,1,7,3,1,2,45

],index=["a","b","c","d","e","f","g","h","j","k"])

In [ ]:
my_series

a     1
b     2
c     5
d     8
e     1
f     7
g     3
h     1
j     2
k    45
dtype: int64

In [ ]:
my_series>4

a    False
b    False
c     True
d     True
e    False
f     True
g    False
h    False
j    False
k     True
dtype: bool

In [ ]:
my_series[my_series>4]=my_series[my_series>4]*3

In [ ]:
my_series['a']

np.int64(2)

In [ ]:
my_series

In [ ]:
data=pd.DataFrame({
    'contry':["Russia","Kazakhstan","Belarus"],
    'population':[144,17,9.5],
    'capital':["Moscow","Astana","Minsk"]

}
,index=["RU","RZ","BY"]

)

In [ ]:
data

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana
BY     Belarus         9.5   Minsk

In [ ]:
data.loc["RU"]

contry        Russia
population     144.0
capital       Moscow
Name: RU, dtype: object

In [ ]:
data.iloc[1]

contry        Kazakhstan
population          17.0
capital           Astana
Name: RZ, dtype: object

In [ ]:
data.index

Index(['RU', 'RZ', 'BY'], dtype='object')

In [ ]:
data.loc[["RU","RZ"]]

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana

In [ ]:
data.loc[["RU","RZ"],"capital"]

RU    Moscow
RZ    Astana
Name: capital, dtype: object

In [ ]:
data["size"]=[17,2.7,0.2]

In [ ]:
data

        contry  population capital  size  population_per_million
RU      Russia       144.0  Moscow  17.0               12.000000
RZ  Kazakhstan        17.0  Astana   2.7                1.416667
BY     Belarus         9.5   Minsk   0.2                0.791667

In [ ]:
data["population_per_million"]=data.population/data.size

In [ ]:
data.drop(["population_per_million"],axis="columns",inplace=True)

In [ ]:
data

        contry  population capital
RU      Russia       144.0  Moscow
RZ  Kazakhstan        17.0  Astana
BY     Belarus         9.5   Minsk

In [ ]:
data.drop(["BY"],inplace=True)

In [ ]:
data

     contry  population capital  size
RU   Russia       144.0  Moscow  17.0
BY  Belarus         9.5   Minsk   0.2

In [ ]:
data[data.population>10].population

RU    144.0
Name: population, dtype: float64

In [ ]:
data['contry']

RU     Russia
BY    Belarus
Name: contry, dtype: object

In [ ]:
titanic=pd.read_csv("/content/Titanic-Dataset.xls")

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.shape

(891, 12)

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
titanic.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
titanic=titanic.drop(["Cabin"],axis="columns")

In [ ]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [ ]:
titanic["Age"]=titanic["Age"].fillna(titanic["Age"].median())

In [ ]:
titanic["Embarked"].fillna(titanic["Embarked"].mode())

In [ ]:
titanic["Embarked"]=titanic["Embarked"].fillna(titanic["Embarked"].value_counts().idxmax())

In [ ]:
titanic.groupby(["Sex","Survived"])

In [ ]:
titanic.groupby(["Sex","Survived"])["PassengerId"].count()

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: PassengerId, dtype: int64

In [ ]:
titanic.groupby(["Pclass","Survived"])["PassengerId"].count()

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: PassengerId, dtype: int64

In [ ]:
titanic.to_excel("/content/Titanic-Dataset-worked.xlsx",index=False)